from matplotlib import rc
import daft

rc("font", family="serif", size=12)
rc("text", usetex=True)

pgm = daft.PGM([3.7, 2.1], origin=[1.65, 0.35], observed_style="inner")
pgm.add_node(daft.Node("theta", r"$\theta$", 2, 1.5, fixed=False))
#pgm.add_node(daft.Node("phi", r"$\phi$", 5, 2, fixed=False))
#pgm.add_node(daft.Node("I", r"$\vec{I}$", 5, 1, observed=True))
pgm.add_node(daft.Node("M", r"$M_k$", 3, 1, fixed=False))
pgm.add_node(daft.Node("Mhat", r"$\hat{M}_k$", 4, 1, observed=True))
pgm.add_node(daft.Node("sigma", r"$\sigma_k$", 3, 2, fixed=False))
pgm.add_node(daft.Node("sigmahat", r"$\hat{\sigma}_k$", 4, 2, observed=True))
pgm.add_edge("theta", "M")
pgm.add_edge("sigma", "M")
pgm.add_edge("M", "Mhat")
pgm.add_edge("sigma", "sigmahat")
#pgm.add_edge("phi", "I")
#pgm.add_edge("I", "Mhat")
#pgm.add_edge("sigmahat", "I")
pgm.add_plate(daft.Plate([2.5, 0.5, 2, 1.85], label=r"galaxies $k$", position='bottom left'))
pgm.render()
pgm.figure.savefig("missing_pgm0.png", dpi=200)

pgm = daft.PGM([3.7, 2.1], origin=[1.65, 0.35], observed_style="inner")
pgm.add_node(daft.Node("theta", r"$\theta$", 2, 1.5, fixed=False))
pgm.add_node(daft.Node("phi", r"$\phi$", 5, 2, fixed=False))
pgm.add_node(daft.Node("I", r"$\vec{I}$", 5, 1, observed=True))
pgm.add_node(daft.Node("M", r"$M_k$", 3, 1, fixed=False))
pgm.add_node(daft.Node("Mhat", r"$\hat{M}_k$", 4, 1, observed=True))
pgm.add_node(daft.Node("sigma", r"$\sigma_k$", 3, 2, fixed=False))
pgm.add_node(daft.Node("sigmahat", r"$\hat{\sigma}_k$", 4, 2, observed=True))
pgm.add_edge("theta", "M")
pgm.add_edge("sigma", "M")
pgm.add_edge("M", "Mhat")
pgm.add_edge("sigma", "sigmahat")
pgm.add_edge("phi", "I")
#pgm.add_edge("sigmahat", "I")
pgm.add_plate(daft.Plate([2.5, 0.5, 2, 1.85], label=r"galaxies $k$", position='bottom left'))
pgm.render()
pgm.figure.savefig("missing_pgm1.png", dpi=200)

pgm = daft.PGM([3.7, 2.1], origin=[1.65, 0.35], observed_style="inner")
pgm.add_node(daft.Node("theta", r"$\theta$", 2, 1.5, fixed=False))
pgm.add_node(daft.Node("phi", r"$\phi$", 5, 2, fixed=False))
pgm.add_node(daft.Node("I", r"$\vec{I}$", 5, 1, observed=True))
pgm.add_node(daft.Node("M", r"$M_k$", 3, 1, fixed=False))
pgm.add_node(daft.Node("Mhat", r"$\hat{M}_k$", 4, 1, observed=True))
pgm.add_node(daft.Node("sigma", r"$\sigma_k$", 3, 2, fixed=False))
pgm.add_node(daft.Node("sigmahat", r"$\hat{\sigma}_k$", 4, 2, observed=True))
pgm.add_edge("theta", "M")
pgm.add_edge("sigma", "M")
pgm.add_edge("M", "Mhat")
pgm.add_edge("sigma", "sigmahat")
pgm.add_edge("phi", "I")
pgm.add_edge("sigmahat", "I")
pgm.add_plate(daft.Plate([2.5, 0.5, 2, 1.85], label=r"galaxies $k$", position='bottom left'))
pgm.render()
pgm.figure.savefig("missing_pgm2.png", dpi=200)

pgm = daft.PGM([3.7, 2.1], origin=[1.65, 0.35], observed_style="inner")
pgm.add_node(daft.Node("theta", r"$\theta$", 2, 1.5, fixed=False))
pgm.add_node(daft.Node("phi", r"$\phi$", 5, 2, fixed=False))
pgm.add_node(daft.Node("I", r"$\vec{I}$", 5, 1, observed=True))
pgm.add_node(daft.Node("M", r"$M_k$", 3, 1, fixed=False))
pgm.add_node(daft.Node("Mhat", r"$\hat{M}_k$", 4, 1, observed=True))
pgm.add_node(daft.Node("sigma", r"$\sigma_k$", 3, 2, fixed=False))
pgm.add_node(daft.Node("sigmahat", r"$\hat{\sigma}_k$", 4, 2, observed=True))
pgm.add_edge("theta", "M")
pgm.add_edge("sigma", "M")
pgm.add_edge("M", "Mhat")
pgm.add_edge("sigma", "sigmahat")
pgm.add_edge("phi", "I")
pgm.add_edge("Mhat", "I")
pgm.add_plate(daft.Plate([2.5, 0.5, 2, 1.85], label=r"galaxies $k$", position='bottom left'))
pgm.render()
pgm.figure.savefig("missing_pgm3.png", dpi=200)

pgm = daft.PGM([3.7, 2.1], origin=[1.65, 0.35], observed_style="inner")
pgm.add_node(daft.Node("theta", r"$\theta$", 2, 1.5, fixed=False))
pgm.add_node(daft.Node("phi", r"$\phi$", 5, 2.1, fixed=False))
pgm.add_node(daft.Node("I", r"$\vec{I}$", 5, 1.3, observed=True))
pgm.add_node(daft.Node("M", r"$M_k$", 3, 1, fixed=False))
pgm.add_node(daft.Node("Mhat", r"$\hat{M}_k$", 4, 0.8, observed=True))
pgm.add_node(daft.Node("sigma", r"$\sigma_k$", 3, 2, fixed=False))
pgm.add_node(daft.Node("sigmahat", r"$\hat{\sigma}_k$", 4, 2, observed=True))
pgm.add_edge("theta", "M")
pgm.add_edge("sigma", "M")
pgm.add_edge("M", "Mhat")
pgm.add_edge("sigma", "sigmahat")
pgm.add_edge("phi", "I")
pgm.add_edge("M", "I")
pgm.add_edge("sigma", "I")
pgm.add_plate(daft.Plate([2.5, 0.5, 2, 1.85], label=r"galaxies $k$", position='bottom left'))
pgm.render()
pgm.figure.savefig("missing_pgm4.png", dpi=200)
