from matplotlib import rc
import daft

rc("font", family="serif", size=12)
rc("text", usetex=True)

pgm = daft.PGM([3.7, 2.7], origin=[1.2, -0.3], observed_style="inner")
pgm.add_node(daft.Node("Omega", r"$\Omega$", 1.5, 1.8, fixed=False))
pgm.add_node(daft.Node("N", r"$N$", 1.55, 0.75, fixed=False))
pgm.add_node(daft.Node("theta", r"$\theta$", 2.1, 1.5, fixed=False))
pgm.add_node(daft.Node("phi", r"$\phi$", 4.1, 0.0, fixed=False))
pgm.add_node(daft.Node("I", r"$I_k$", 4.5, 1.5, observed=True))
pgm.add_node(daft.Node("y", r"$y_k$", 3, 1, fixed=False))
pgm.add_node(daft.Node("yhat", r"$\hat{y}_k$", 3.85, 1, observed=True))
pgm.add_node(daft.Node("x", r"$x_k$", 3, 2, fixed=False))
pgm.add_node(daft.Node("xhat", r"$\hat{x}_k$", 3.85, 2, observed=True))
pgm.add_node(daft.Node("Ndet", r"$N_{det}$", 2.5, 0.0, observed=True))
pgm.add_edge("theta", "y")
pgm.add_edge("x", "y")
pgm.add_edge("x", "xhat")
pgm.add_edge("y", "yhat")
pgm.add_edge("phi", "I")
pgm.add_edge("phi", "Ndet")
pgm.add_edge("theta", "Ndet")
pgm.add_edge("Omega", "Ndet")
pgm.add_edge("N", "Ndet")
pgm.add_edge("Omega", "x")
pgm.add_edge("yhat", "I")
pgm.add_plate(daft.Plate([2.5, 0.5, 2.35, 1.85], label=r"clusters $k$", position='bottom left'))
pgm.render()
pgm.figure.savefig("missing_truncy_pgm.png", dpi=200)

pgm = daft.PGM([3.7, 2.7], origin=[1.2, -0.3], observed_style="inner")
pgm.add_node(daft.Node("Omega", r"$\Omega$", 1.5, 1.8, fixed=False))
#pgm.add_node(daft.Node("N", r"$N$", 1.55, 0.75, fixed=False))
pgm.add_node(daft.Node("theta", r"$\theta$", 2.1, 1.5, fixed=False))
#pgm.add_node(daft.Node("phi", r"$\phi$", 4.1, 0.0, fixed=False))
#pgm.add_node(daft.Node("I", r"$I_k$", 4.5, 1.5, observed=True))
pgm.add_node(daft.Node("y", r"$y_k$", 3, 1, fixed=False))
pgm.add_node(daft.Node("yhat", r"$\hat{y}_k$", 3.85, 1, observed=True))
pgm.add_node(daft.Node("x", r"$x_k$", 3, 2, fixed=False))
pgm.add_node(daft.Node("xhat", r"$\hat{x}_k$", 3.85, 2, observed=True))
#pgm.add_node(daft.Node("Ndet", r"$N_{det}$", 2.5, 0.0, observed=True))
pgm.add_edge("theta", "y")
pgm.add_edge("x", "y")
pgm.add_edge("x", "xhat")
pgm.add_edge("y", "yhat")
#pgm.add_edge("phi", "I")
#pgm.add_edge("phi", "Ndet")
#pgm.add_edge("theta", "Ndet")
#pgm.add_edge("Omega", "Ndet")
#pgm.add_edge("N", "Ndet")
pgm.add_edge("Omega", "x")
#pgm.add_edge("yhat", "I")
pgm.add_plate(daft.Plate([2.5, 0.5, 2.35, 1.85], label=r"clusters $k$", position='bottom left'))
pgm.render()
pgm.figure.savefig("missing_complete_pgm.png", dpi=200)
